apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-endpointslice
  namespace: my-namespace
addressType: IPv4
ports:
- name: http
  port: 80
endpoints:
- addresses:
  - "192.0.2.1"
