apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: my-mutating-webhook
webhooks:
- name: mywebhook.example.com
  clientConfig:
    service:
      name: my-service
      namespace: my-namespace
      path: "/mutate"
    caBundle: <base64-encoded-ca-bundle>
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
