apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: my-validating-webhook
webhooks:
- name: mywebhook.example.com
  clientConfig:
    service:
      name: my-service
      namespace: my-namespace
      path: "/validate"
    caBundle: <base64-encoded-ca-bundle>
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
