apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: my-alerts
  namespace: my-namespace
spec:
  groups:
  - name: example
    rules:
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total[5m])) by (pod) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected"
