apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: my-csr
spec:
  request: <base64-encoded-request>
  signerName: kubernetes.io/kubelet-serving
  usages:
  - digital signature
  - key encipherment
