apiVersion: secrets-store.csi.k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secret-provider
  namespace: my-namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "my-keyvault"
    objects: |
      array:
        - |
          objectName: my-secret
          objectType: secret
